export const projects = [
  {
    id: 0,
    title: "Project 1",
    description: "Project 1 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "13.02.22",
  },
  {
    id: 1,
    title: "Project 2",
    description: "Project 2 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "01.20.23",
  },
  {
    id: 2,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 3,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 4,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 5,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 6,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 7,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 8,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 9,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 10,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 11,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 12,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 13,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 14,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 15,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 16,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 17,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 18,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
  {
    id: 19,
    title: "Project 3",
    description: "Project 3 description",
    customer: "Customer 1",
    url: "/project.png",
    year: "21.07.25",
  },
];
